В языке Python все ошибки являются исключениями, но не все исключения являются ошибками. встроенная функция input читает по одной строке текста при каждом вызове из стандартного потока ввода sys.stdin и возбуждает исключение EOFError по достижении конца файла.  

исключение EOFError в данном контексте – это всего лишь сигнал, а не ошибка. По этой причине чтобы избежать преждевременного
завершения работы сценария, функцию input обертывают инструкцией try, которую вкладывают в цикл, как показано ниже:  

                                    while 1:
                                        try:
                                            line = input() # Прочитать строку из потока stdin
                                        except EOFError:
                                            break # Выход по достижении конца файла
                                        else:
                                            ...обработка следующей строки...  

Существуют и другие встроенные исключения, которые являются сигналами, а не ошибками, – вызов функции sys.exit() и нажатие комбинации клавиш Ctrl-C, например, возбуждают исключение SystemExit и KeyboardInterrupt соответственно. В языке Python имеется также ряд встроенных исключений, которые являются скорее предупреждениями, чем ошибками. Дополнительная информация  по предупреждениям - в модуле warnings.  

**Подробнее о функции sys.exc_info**  
Функция sys.exc_info позволяет обработчикам исключений получить доступ к последнему возбужденному исключению.  

Если в момент ее вызова никакое исключение не обрабатывается, функция возвращает кортеж с тремя объектами None. В противном случае возвращаются (тип, значение, трассировочная_информация), где:  
 - Тип – это класс обрабатываемого исключения.  
 - Значение – это экземпляр класса возбужденного исключения.  
 - Трассировочная информация – это объект, который представляет стек вызовов в точке, где возникло исключение.  

